### ISSUE TITLE
http2 acceptance?

### ISSUE THREAD

**Issue by knoxcard** [Daplie/greenlock-express#100]
Does this work with http2 as well?  My apologies if this is the wrong place to post this.  This really not an issue, more of a question.  If the answer is no, I guess it therefore becomes an issue.

**Comment by insightfuls** [comment]
This isn't really determined by this software, but by NodeJS or the module you are using to serve HTTP(S). I believe NodeJS doesn't support HTTP 2 in core yet, and this software uses core. However, there's nothing stopping you hooking the middleware and/or httpsOptions (SNI callback) from here to another module that provides HTTP 2 support, instead of core HTTP(S), and everything should work fine.

**Comment by coolaj86** [comment]
You can use this with any node http 2 module that supports the same format of tls options that node's native http module supports.
