### ISSUE TITLE
This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand

### ISSUE THREAD

**Issue by timomitt2610** [Daplie/greenlock-express#111]
I get this info to console when creating new certificate:

```
This Let's Encrypt / ACME server has been updated with urls that this client doesn't understand
{ 'key-change': 'https://acme-staging.api.letsencrypt.org/acme/key-change',
'new-authz': 'https://acme-staging.api.letsencrypt.org/acme/new-authz',
'new-cert': 'https://acme-staging.api.letsencrypt.org/acme/new-cert',
'new-reg': 'https://acme-staging.api.letsencrypt.org/acme/new-reg',
'revoke-cert': 'https://acme-staging.api.letsencrypt.org/acme/revoke-cert' }
[pyconf] WARN index past array length:
68 68 undefined
unexpected duplicate key 'keyPath': '/root/letsencrypt/etc/live/www.causticsoda.com.au/privkey.pem'
unexpected duplicate key 'checkpoints': '0'
unexpected duplicate key 'account': '4fac1f4c99d116d26e1d8f689588036e'

[pyconf] WARN index past array length:
68 68 undefined
unexpected duplicate key 'keyPath': '/root/letsencrypt/etc/live/causticsoda.com.au/privkey.pem'
unexpected duplicate key 'checkpoints': '0'
unexpected duplicate key 'account': '4fac1f4c99d116d26e1d8f689588036e'
```

It creates the certificate, but when going to the site it shows it is not secure due to invalid/unknown authority/issuer.

**Comment by insightfuls** [comment]
Everything you're seeing there is harmless.

It will be showing as insecure because you're using the staging server. However, if you click for more details in your browser and view the certificate, you should see that it's issued by the Let's Encrypt Staging server, so you know it has worked. Once you are satisfied it's working, not renewing too often, etc., you can switch to the live server and it will show as fully secure.

**Comment by timomitt2610** [comment]
Thank you for the answer. I tried to set server to https://acme-v01.api.letsencrypt.org/directory previously, but still did not work, but I guess it's because I changed some other params as well. It works now. Thanks!
